baseurl = "https://www.rostrum.blog/"
languageCode = "en-gb"
title = "rostrum.blog"
theme = "hugo-lithium-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    
[params]
    description = "Fun and learning with #rstats"

    customCSS = ["css/extra.css"]
    


    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = ""

