---
title: Mail merge in 2018
author: Matt Dray
date: '2018-06-22'
slug: mail-merge-in-2018
categories:
  - R
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

<span style="color:lightgray">Matt Dray</span>

Clip art. Fax machines. CD-ROMs. 56k modems. Desktop Publishing. The World Wide Web. *Mail merge*.

These exotic terms may give you flashbacks to your ICT class at the turn of the millennium.

The last one -- mail merge -- is a technique you might still need to use. It involves filling a template document, typically a letter, with information from unique cases in a database.

I've had to do something like this a few times recently, so [as David Robinson said](https://twitter.com/drob/status/928447584712253440):

> When you’ve given the same in-person advice 3 times, write a blog post

# You will need

Your working directory should contain three important files:

* your letter or report template (.Rmd)
* your style document (.docx)
* a file for reading data and looping through X (.R)

The folder should also contain:

* your R Project file (.Rproj)
* a folder to hold the output files
* any additional folders you need for input files (e.g. data and images)

## The template

This is the file containing the actual content of your letter or report.

## The style

The default output from an R Markdown file to a Word document isn't great. You can create a separate Word document that contains modified styles to match the theme.

```
---
output:  
  word_document:
    reference_docx: style_reference.docx
---
```

## The loop

For each X in some vector of things, render the R Markdown template file according to the style document and save it with a unique name

```
for (i in unique(dataset$urn)){  # loop through each element from the dataset
 
  data <- dataset[dataset$urn == i, ]  # isolate the row for that URN
 
  # the dataframe object 'data' we just created will be used as the source
  # for filling the details in on the template
 
  # now render ('knit') the R Markdown file to Word format, name it and save it
 
  render(
    "01_template.rmd",  # where to source the template from
    output_file = paste0("report_", i, ".docx"),  # name the output
    output_dir = "output"  # folder to put the output file
  )
}
```

# Execute

Run the loop. The files will be output in turn to the output folder.