---
title: Waggle dance with ggbeeswarm and emoGG
author: Matt Dray
date: '2018-11-21'
slug: waggle-dance
categories:
  - dataviz
  - R
tags:
  - ggbeeswarm
  - ggplot2
  - magick
  - bees
  - entomology
draft: yes
---

```{r packages}
library(ggplot2)
library(emoGG)
library(ggbeeswarm)
library(magick)
```

```{r geom_quasirandom}
geom_quasi_emoji <- function (mapping = NULL, data = NULL, width = NULL, varwidth = FALSE, 
          bandwidth = 0.5, nbins = NULL, method = "quasirandom", groupOnX = NULL, 
          dodge.width = 0, stat = "identity", position = "quasirandom", 
          na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, emoji = "1f4l1d", ...) {
  
  img <- emoji_get(emoji)[[1]]
  
  position <- position_quasirandom(width = width, varwidth = varwidth, 
                                   bandwidth = bandwidth, nbins = nbins, method = method, 
                                   groupOnX = groupOnX, dodge.width = dodge.width)
  
  ggplot2::layer(data = data, mapping = mapping, stat = stat, 
                 geom = emoGG:::GeomEmoji, position = position, show.legend = show.legend, 
                 inherit.aes = inherit.aes, params = list(na.rm = na.rm, img = img, ...))
}

```

```{r data}
swarm <- data.frame(
  "variable" = rep(c("runif", "rnorm"), each = 100),
  "value" = c(runif(100, min = -3, max = 3), rnorm(100))
)
```

```{r ggplot}
p <- ggplot2::ggplot(swarm, ggplot2::aes(variable, value)) +
  geom_quasi_emoji(emoji = "1f41d", method = "pseudorandom") +
  theme(panel.background = element_rect(fill = "skyblue")) +
  ggtitle("WAGGLE DANCE")
```

```{r plot_panels}
my_res = 100
my_width = 400
my_height = 400

t1 <- image_graph(width = my_width, height = my_height, res = my_res)
p
dev.off()

t2 <- image_graph(width = my_width, height = my_height, res = my_res)
p
dev.off()

t3 <- image_graph(width = my_width, height = my_height, res = my_res)
p
dev.off()

t4 <- image_graph(width = my_width, height = my_height, res = my_res)
p
dev.off()
```

```{r animate}
waggle_dance <- image_animate(c(t1, t2, t3, t4), fps = 10)
waggle_dance
```

```{r save, eval=FALSE}
image_write(waggle_dance, "~/Desktop/waggle_dance.gif")
```