---
title: Fledgling R Packages
author: Matt Dray
date: '2019-08-10'
slug: fledgling-r-packages
categories:
  - R
  - coding
tags:
  - package
draft: yes
---

This is a post to help jog my memory in future, but you may find it useful.

# 

At some point a useR will want to wrap up their reusable functions into a package, but package building can seem daunting.

I learnt how to create an R package by reading [Hilary Parker](https://twitter.com/hspter)'s now classic [blog post for beginners](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/).

[Tom Westlake](https://twitter.com/tomwestlake121) has [updated the advice](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/) with references to the [{usethis} package](https://usethis.r-lib.org/), which abstracts away some tedious setup tasks

I'm assuming you now have a minimal package with some functions and documentation and that it's on GitHub or wherever.

What next?

# Spread your wings

Hilary's example package used a cat-promoting function; Tom stoked a flamewar by using a dog-related one. I'm not going to get involved, but I will use a bird analogy.


## Tests

* {testthat}, Travis and Codecov

## More {usethis}

* code of conduct
* vignette
* data

## Communication

Prettiness
* {pkgdown}
* {hexSticker}

# And then?

CRAN!

