---
title: A year of rostrum.blog
author: Matt Dray
date: '2019-04-11'
slug: one-year
categories: []
tags: []
draft: yes
---

Matt Dray ([\@mattdray](https://www.twitter.com/mattdray))

# rostrum.blog is a year old `r emo::ji("tada")`

27 posts, about once every two weeks.

<details><summary>Code</summary>
```{r message=FALSE}
# Load packages
library(dplyr)  # data manipulation
library(rvest)  # web scrape
library(stringr)  # string manipulation
library(lubridate)  # deal with dates
library(ggplot2)  # plots
library(plotly)  # interactive plots

# Scrape the rostrum.blog home page
html <- read_html("https://rostrum.blog/")

# Extract the post titles
title <- html %>%
  html_nodes(".archive-item-link") %>%
  html_text()

# Extract the post dates
date <- html %>%
  html_nodes(".archive-item-date") %>%
  html_text() %>%
  str_replace_all("\n|[:space:]", "")

# Dataframe of titles and dates
posts <- tibble(title = title, publish_date = date) %>% 
  mutate(publish_date = ymd(date)) %>% 
  arrange(publish_date)

# Create plot object
p <- posts %>%
  mutate(count = 1) %>%   # dummy to indicate a post was made
  ggplot(aes(x = publish_date, y = count, label = title)) +
  geom_point(color = "#1D8016") +
  theme_void() +  # strip plot elements
  theme(panel.grid = element_blank())  # to stop plotly rendering grid

# Pass the plot object to plotly (actually performed outside this code chunk)
# ggplotly(p, tooltip = c("publish_date", "title")) %>%
#   config(displayModeBar = F)

# Print session info
xfun::session_info()
```
</details>

```{r echo=FALSE, fig.height=0.5}
# Pass the plot object to plotly
ggplotly(p, tooltip = c("publish_date", "title")) %>%
  config(displayModeBar = F)
```