---
title: 'Deer-vehicle collisions: a Shiny app'
author: Matt Dray
date: '2019-01-12'
slug: deer-collisions
categories:
  - dataviz
  - app
tags:
  - shinydashboard
  - shiny
  - scotland
  - deer
  - vehicles
  - leaflet
  - datatable
draft: yes
---

Matt Dray ([\@mattdray](https://www.twitter.com/mattdray))

# Open data

Deer roam Scotland. So do humans. It's a problem when they meet at high speed.

[The National Deer-Vehicle Collisions Project](http://www.deercollisions.co.uk/), administered by [The Deer Initiative](http://www.thedeerinitiative.co.uk/), has been monitoring data on deer-vehicle collisions in the UK.

The data are open. I found the dataset when skimming through [data.gov.uk](https://data.gov.uk/dataset/838b88d8-7509-435c-9649-90f1881b5ad7/deer-vehicle-collisions) (a classic weekend activity for all the family). It links to the [SNH Natural Spaces site](https://gateway.snh.gov.uk/natural-spaces/dataset.jsp?dsid=DVC) where you can download the data as shapefile, GML or KML under the [Open Government Licence](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).

I couldn't find an interactive visualisation of these data and I don't spend much time working with R Shiny,[^wc-18] so why not.

# A simple Shiny app

The app is [live at mattdray.shinyapps.io/scot-deer-collisions/](https://mattdray.shinyapps.io/scot-deer-collisions/).

The [code for the app is available on GitHub](https://github.com/matt-dray/scot-deer-collisions). You can also [download the cleaned data in CSV or RDS format](https://github.com/matt-dray/scot-deer-collisions/tree/master/data).

It's built in R with:

* Shinydashboard for a nice layout and value boxes
* Leaflet for the interactive map
* DT for the interactive datatable


# Limitations

I may update the app in future or take it down entirely. [The code will continue to exist on GitHub](https://www.github.com/matt-dray/scot-deer-collisions) where you can leave an issue or fork it to make it better.

I limited the filters to year, month and local authority. I could have included deer species and road, but the data are sparse and the formatting wasn't great. I cleaned these variables up a bit and they're available as filterable columns in the table.

There's a large number of points and it doesn't make sense to show them all at once because it slows the app down. There are methods for improving this, but I assume most people will be looking at specific local authorities or roads rather than the country as a whole.

I had originally intended for this to be a tool built with Flexdashboard and Crosstalk -- which would have allowed for linked brushing -- but browsers would ismply crash once a certain number of points were on screen.

[^wc-18]: But see [this post about a Shiny app](https://www.rostrum.blog/2018/07/17/world-cup-age-app/) I made that that one colleague described as 'very depressing'.