---
title: '{usethis} for easier R-package building'
author: Matt Dray
date: '2019-11-01'
slug: usethis
categories:
  - code
  - tutorial
  - package
  - talk
tags:
  - cats
  - devtools
  - git
  - github
  - glue
  - pkgdown
  - roxygen2
  - testthat
  - usethis
  - xaringan
draft: yes
---

# tl;dr

You can make an R package with `usethis::create_package()`, `usethis::create_r()` and `devtools::document()`.

{usethis} has a bunch of other really useful functions to add internal documentation, long-form documentation, testing, version control, uploads to GitHub and more.

# Coffee packaging

I gave a talk at a [Cabinet Office Coffee & Coding session](https://co-analysis.github.io/co-coffee-and-coding/) about building R packages. The emphasis was on the {usethis} package for doing the heavy lifting of package development.

Click on the slides embedded below and cycle through with your arrow keys, or [you can open them fullscreen in a dedicated browser tab](https://matt-dray.github.io/r-pkg-slides/#1). Press 'P' to see presenter notes.

<iframe src="https://matt-dray.github.io/r-pkg-slides/" width="700" height="525" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

# The demo package

In the session I live-built a package called {cabinet} and pushed it to GitHub. You can:

* look at the package's [source code](https://github.com/matt-dray/cabinet/)
* see the package's [website](https://matt-dray.github.io/cabinet/), made with {pkgdown}
* install the package with `remotes::install_github("matt-dray/cabinet")`

# Excellent resources

Some useful tutorials for package development:

* Hilary Parker's [post](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) (beginner)
* Tomas Westlake's [update](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/) (beginner)
* Karl Broman's [site](https://kbroman.org/pkg_primer/) (intermediate)
* Hadley Wickham's [book](http://r-pkgs.had.co.nz/) (intermediate/advanced)

Tom's post is probably the best place to start if you want to create a package with {usethis}.