---
title: A pivotal change to Software Carpentry
author: Matt Dray
date: '2019-11-20'
slug: pivot
categories:
  - code
  - teaching
tags:
  - pivot
  - software carpentry
  - the carpentries
  - tidyr
draft: yes
---

# Instructor

I passed [the requirements](https://carpentries.github.io/instructor-training/checkout/) to become a [Software Carpentry](https://software-carpentry.org/) trainer, which ‘teach[es] foundational coding and data science skills to researchers worldwide’ as part of [The Carpentries](https://carpentries.org/) initiative.

I wrote about part of this experience in [a post about live coding](https://www.rostrum.blog/2019/09/12/live-code/) ([cross-posted on The Carpentries blog](https://carpentries.org/blog/2019/09/live-coding-experience/)). The ‘code-along’ format is an important part of the teaching approach for The Carpentries.

# Contribution

A great thing about the The Carpentries is that the lessons are openly available on GitHub. 

One of the instructor assessment requirements is to make a contribution to develop the materials. This can be as simple as raising an issue on GitHub or offering a pull request (PR) to merge in new or amended content.

I made a [trivial PR](https://github.com/swcarpentry/r-novice-gapminder/pull/569) to correct a small problem with bullet points, but I had [a more substantial suggestion that I raised in in an issue](https://github.com/swcarpentry/r-novice-gapminder/issues/570): to update the entire episode about [{tidyr}](https://tidyr.tidyverse.org/), a [tidyverse](https://www.tidyverse.org/) package used for reshaping data frames.

# Pivot

Why? Since {tidyr} [version 1.0.0](https://www.tidyverse.org/blog/2019/09/tidyr-1-0-0/), the `pivot_longer()` and `pivot_wider()` functions have replaced the `spread()` and `gather()` functions. Their aim is to be more intuitive. Hadley Wickham, the package’s creator, has said that even he had to look up the syntax for `spread()` and `gather()` before using them.

What do these functions do? They switch data frames between ‘wide’ and ‘long’ forms form. For example, a long data set might have a column called ‘year’ and a column called ‘population’. A wide version would have separate columns named for each year (‘1994’, ‘1995’, etc) that each contained that year’s ‘population’ figures.

The `pivot_wider()` function spreads long data into wide form and `pivot_longer()` gathers the data into long form. See how the names are more intuitive? [Hadley did a little poll](https://github.com/hadley/table-shapes) to see how people referred to these two table shapes and ‘wider’ and ‘longer’ were most popular.

Some helpful explainers on this topic are:

* [the {tidyr} vignette about pivoting](https://tidyr.tidyverse.org/dev/articles/pivot.html)
* Hiroaki Yutani’s [slides](https://speakerdeck.com/yutannihilation/a-graphical-introduction-to-tidyrs-pivot-star) — ‘A graphical introduction to tide’s pivot_*()’
* Bruno Rodrigues’s [blogpost](https://www.brodrigues.co/blog/2019-03-20-pivot/) — ‘Pivoting data frames just got easier thanks to `pivot_wide()` and `pivot_long()`’
* Sharon Machlis’s [video](https://youtu.be/gnUgSkKEW5c) — ‘How to reshape data with tidyr’s new pivot functions’
* Gavin Simpson’s [blog](https://www.fromthebottomoftheheap.net/2019/10/25/pivoting-tidily/) — ‘Pivoting tidily’ (a real-world problem)

# Re-writing the episode

So was this as simple as finding and replacing `spread()` with `pivot_longer()` and `gather()` with `pivot_wider()`? 

No.
