---
title: 'Git going: Git and GitHub'
author: Matt Dray
date: '2019-08-17'
slug: git-going-basics
categories:
  - code
  - tutorial
tags:
  - bash
  - git
  - github
  - terminal
  - shell
  - version control
draft: yes
---

# tl;dr

This post is a basic and non-comprehensive introduction to Git and GitHub, with a focus on Mac users working alone on a project. Here's a quick reference for some commonly-used Git commands:

| Command                     | Short explanation                           |
| :-------------------------- | :------------------------------------------ |
| `git init`                  | Put a folder under version control with Git |
| `git status`                | Show changes                                |
| `git add <file>`            | Confirm the changes to be committed         |
| `git commit -m "<message>"` | Commit the changes with an explanation      |
| `git push origin master`    | Send your commits to GitHub                 |


# Git and GitHub

Git is a version control system that tracks file changes on your computer, records why they were made and lets you revert to a past state if something goes wrong.

GitHub is a website where you can store the Git history of your files remotely on the web [^remotes]. It acts as a back-up for your work and its versions; lets you explore your code in your browser in a more visual and interactive way; lets other people see your code in the open and use it themselves; lets you record issues and to-do items; and much, much more.

Our goal in this post is to put a project folder under version control with Git and then upload it to GitHub. I assume you're a beginner and are, for now, working alone on a project.[^audience]

We'll be using the command line to do all of this. This is the place where you write code to tell your computer what to do, which you can access via software like ['Terminal' on a Mac](https://en.wikipedia.org/wiki/Terminal_(macOS)). You may want to [see my earlier post for how to get basic stuff done with the command line](https://www.rostrum.blog/2019/02/01/git-going-cl/) before you continue.

It's okay if you aren't comfortable using the command line. The bottom line is to get your work under some form of version control. You could always use GitHub's drag and drop interface without needing to use the command line at all.

# Step-by-step

The steps below summarise what you need to do to set up and use Git and GitHub. I've split the steps into broad stages. Click a link to jump to that section.

[One-time tasks](#one-time):

* [Install Git](#install)
* [Create a GitHub account](#github-account)

[Project set-up](#project-setup):

1. [Create your project folder](#folder)
1. [Initiate Git](#init)
1. [Create a .gitignore file](#gitignore)

[A Git/GitHub workflow](#git-github-workflow) (you'll repeat these steps as you develop your project):

1. [Work on your files](#work)
1. [Check file status](#status)
1. [Add changes](#add)
1. [Commit changes](#commit)
1. [Push changes to GitHub](#push)

## One-time tasks {#one-time}

### Install Git {#install}

You can check if Git is installed by typing `git --version` at the command line. If you get a response like `git version 2.23.0`, then it's already installed.

If not, you can [download it from the Git website](https://git-scm.com/downloads) and install it.

Note that Git is not an 'app'; there's not an icon for it on your computer. It's a bunch of functions installed for use via the command line, with each command preceded with the word `git`.

Now you need to shake hands with Git so it remembers who you are. You do this by altering some configuration files like so:

```{sh eval=FALSE}
git config --global user.name '<Your Name>'
git config --global user.email '<youremail@address.com>'
git config --global --list
```

### Create a GitHub account {#github-account}

GitHub is free to use but you need an account.

To make one, go to the [GitHub website](https://github.com/) and click 'Sign-up for GitHub'. You'll need to provide a username (think hard about this), email address and password.

When prompted for a subscription level, choose 'free subscription'. You'll be able to do everything you need to do with this type of account; a premium account is more suitable for teams.

You'll be sent an automated email to verify your email address. Click the button in the email to confirm.

You don't need to do anything else right now. Just check that your GitHub profile page is viewable at `github.com/yourusername` once you've compeleted these steps.

## Project set-up {#project-setup}

The following subsections are about creating a project folder and putting it under version control by activating Git.

### Create your project folder {#folder}

It's good practice for a self-contained project to exist in a single folder, so all the code, data, tests and documentation are in the same place. Let's create a project folder now.

In [part one of this 'Git going' series](https://www.rostrum.blog/2019/02/01/git-going-cl/) you learnt how to navigate your computer's filesystem from the command line. We'll be using that knowledge here, so you may want to revisit.

At the command line:

1. Provide to `cd` the filepath where you want your project folder to be created (e.g. `cd ~/Documents`)
1. Create the project folder with `mkdir` (e.g. `mkdir project-name`)
1. Enter this new folder with `cd` (e.g. `cd project-name`)
1. Run `pwd` to print your working directory, which should be your newly-created project folder (subsequent Git commands will therefore be applied to this folder, which is what we want)

You could also create a new folder by pointing and clicking; just make sure you navigate to the folder at the command line

### Initiate Git {#init}

So we have our empty project folder, but it's not yet under version control. How can we make Git aware of this folder and start tracking changes?

Type `git init` to initiate Git in the project folder. You'll get something like `Initialized empty Git repository in /Users/luigi/Documents/project/.git/` if it was successful.

What did this do? Run `ls -a` to list all the files in the folder. You'll see there's now a hidden `.git` folder (files preceded with a period aren't visible by default). It's hidden because it's going to run in the background and you can forget about it for now.

### Create a .gitignore file {#gitignore}

There are files that you may not want to commit. This might include sensitive files, large data sets or language-specific artefacts.

You can leave instructions in a special 'gitignore' file that tells Git not to worry about recording certain things.

While still in the root of the project directory, add a gitignore file by typing `touch .gitignore` at the command line. Typing `open .gitignore` (note the period because this too is a hidden file) will open it in your computer's default text editor for editing (or you can [edit from the command line itself](https://www.rostrum.blog/2019/02/01/git-going-cl/#createedit-a-file-with-touchnano)). Now you can add specific files and file types to the .gitignore so that they'll be ignored.

You could start by copying from [a .gitignore template](https://github.com/github/gitignore), like [the one for R](https://github.com/github/gitignore/blob/master/R.gitignore). For example, the first thing in this template is `.Rhistory` -- a log of all the commands you've typed -- which you probably don't need to have tracked.

You could add things like `secret.csv` to ignore a specific dataset, or `*.csv` (meaning any filename that ends with `.csv`) to ignore all CSV files. Mac users will also want to add `.DS_Store`, which is [a kind of Mac-specific metadata file](https://en.wikipedia.org/wiki/.DS_Store).

Note that we haven't recorded any changes to the folder with Git yet. Let's add some analysis files to the folder first. 

### Add files {#work}

Let's say we create a couple of files for our analysis so the file tree ends up looking like this:

project/
  analysis.R
  data/
    data.csv
  .git
  .gitignore

Great, let's capture this version with Git.

## The Git/GitHub workflow {#git-github-workflow}

A basic Git workflow might look like this:

1. Add/edit your files
1. from the command line, run `git status` to check which files have been changed
1. `git add <filename>` to 'stage' changes
1. `git commit -m "Message"` to confirm the additions and record why the changes were made
1. `git push origin master` to send a record of the changes to GitHub

### Check file status {#status}

Type `git status` to see the files that have been created or modified.

You'll get output like:

```{sh eval=FALSE}
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        created:    data/data.csv
        created:    analysis.R
        created:    .gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

You can see on the indented lines the files that are new or have been changed since last time. All the files will be new the first time you run this process, of course.

Note that any files that are in your .gitignore will not appear here. They've been ignored, of course.

```{sh eval=FALSE}
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        created:    readme.md
        modified:   analysis.R
        modified:   data/data.csv

no changes added to commit (use "git add" and/or "git commit -a")
```

### Add changes {#add}

Now you need to earmark the files whose changes you want to record. This process is called staging. The stage is a safe place where you can add files to be captured; they're not yet confirmed. This is a preventative measure so you don't accidentally record anything you didn't mean to.

There was a handy reminder in the output of `git status` that tells you what to do next: `use "git add <file>..." to update what will be committed`. In other words, you can type the names of the files you want to record with `git add`:

```{sh eval=FALSE}
git add readme.md analysis.R data/data.csv
```

You could also use `git add .`, where the period means 'all the files'. Be careful if you use this -- you don't want to end up capturing things you didn't mean to.

You won't get any output, so how do we know this worked? Type `git status` again.

```{sh eval=FALSE}
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        created:    analysis.R
        created:    data/data.csv
        created:    .gitignore
```

These files are now staged and marked as 'changes to be committed'.

If you made a mistake and want to remove files from the stage, you can type `git reset HEAD <filename>`. This line is helpfully printed in the output from `git status`..

### Commit changes {#commit}

When you're happy with the files that have been staged, you can now commit them. This confirms that you want Git to record the changes made to these files.

You commit the staged changes using `git commit`. It's good practice to leave a message explaining what changes were made and why. You can leave a simple message using the `-m` flag of `git commit`:

```{sh eval=FALSE}
git commit -m "Add files to the repository"
```

The message should be short (typically less than 50 characters) but informative (not just 'changed stuff').[^commit-msg] 

How often should you make commits? It's up to you, but it's probably a good idea to do it when you've completed a section of code that does something useful and that you might want to revert to if there's a problem later. It's less useful to commit on a time schedule with code expresssions that may be incomplete.

### Add and edit some more

Continue to add and edit files, committing them when necessary. Remember to use `git status` to check what changes have been made.

### Push changes to GitHub {#push}

Our commits are stored locally. How do we send them to GitHub so we have a remote copy of our version history? We push them.

```{sh eval=FALSE}
git push
```

[^audience]: In fact, the real audience are the participants of the UK government's [Data Science Accelerator](https://www.gov.uk/government/publications/data-science-accelerator-programme/introduction-to-the-data-science-accelerator). Participants are analysts who may have little knowledge of programming.
[^remotes]: Other services are available, like [GitLab](https://about.gitlab.com/) and [BitBucket](https://bitbucket.org/), but we'll focus on GitHub.
[^commit-msg]: You can also commit with both a short message and a longer description. To do this, run `git commit` wihtout the `-m` flag. By default on macOS this will open Vim, a text editor, inside Terminal. Type in your comments and then type <kbd>Esc</kbd> <kbd>:</kbd> <kbd>w</kbd> <kbd>q</kbd> to 'write-quit' (save and exit) and return to the command line.