---
title: Teach a man to swirl
author: Matt Dray
date: '2019-04-30'
slug: teach-a-man-to-swirl
categories:
  - R
  - teaching
tags:
  - swirl
  - swirlify
---

* [swirl site](https://swirlstats.com/)
* [How to use](https://swirlstats.com/students.html)
* [Overview for course creators](https://swirlstats.com/instructors.html)
* [Full swirlify guidance](http://swirlstats.com/swirlify/)

# Message

* Teach people to teach people; it's more efficient
* Create materials that aren't just static documents
* {swirl} forces people to actually interact with R
* {swirlify} makes it easy to create {swirl} materials; you can even use a GUI

# Structure

1. Give a person a fish: {swirl} is a way to learn about R from within R (this is the place to start if you're an R beginner or just want to learn some).
1. Teach a person to fish: {swirlify} is a way to create materials for {swirl}.

# Content

* Discuss approaches to learning R
* Interactive methods are more effective (blogpost/walkthrough < {learnr} doc < Coursera-style < {swirl}-like?)
* I think interacting with R to learn R makes sense
* There are limited options for this; {swirl} is a good option and is 'plug and play' so you download other people's courses
* Run-through of using {swirl}, including downloading a course and use of `play()`, `bye()`, etc.
* {swirlify} lets you create {swirl} your own swirl courses; you can even do it via GUI
* You can write something for the community and contribute it to the swirl course network, or you can easily distribute it yourself (.swc single file or store the materials on DropBox, Google Drive, or even better, GitHub – there are functions to install courses directly from these sources)
* Run-through of using {swirlify} to create a course (including the directory structure and YAML, etc)
* Installing and using your course from GitHub

# A workflow
