---
title: The Mountain Goats with {spotifyr}
author: Matt Dray
date: '2019-04-23'
slug: mountain-goats
categories:
  - R
  - pop culture
tags:
  - spotifyr
  - the mountain goats
  - music
---

```{r message=FALSE}
library(dplyr)
library(spotifyr)
library(lubridate)
access_token <- get_spotify_access_token()
```

# Get albums

```{r}
goat_albums <- get_artist_albums(
  id = "3hyGGjxu73JuzBa757H6R5",
  include_groups = "album",
  limit = 25,
  market = "GB"
) %>% 
  select(id, name, release_date) %>% 
  filter(name != "Goths (Deluxe Version)") %>% 
  mutate(release_date = substr(release_date, 1, 4))

# dedupe_album_names(
#   df = goat_albums,
#   album_name_col = "name",
#   album_release_year_col = "release_date"
# )

goat_albums
```

# Get album songs

```{r}
tracks <- purrr::map_df(goat_albums$id, get_album_tracks)
get_track_audio_features(tracks$id[1:100])
get_track_audio_features(tracks$id[101:200])
get_track_audio_features(tracks$id[201:300])
get_track_audio_features(tracks$id[301:312])
```
