---
title: Hit your reproducibility {targets}
author: Matt Dray
date: '2020-09-25'
slug: targets-dsfest
categories:
  - code
  - event
  - tutorial
tags:
  - conference
  - drake
  - r
  - reproducibility
  - targets
draft: yes
---

# tl;dr

I spoke at the UK Government Data Science Festival about the R package [{targets}]() for workflow reproducibility by [Will Landau]().

# Slides

You can see the slides [in a dedicated browser window](https://matt-dray.github.io/targets-dsfest/#1) and [visit the source](https://github.com/matt-dray/targets-dsfest).

Press <kbd>P</kbd> for presenter notes, <kbd>O</kbd> for a slide overview and <kbd>F</kbd> for fullscreen.

```{r slides, echo=FALSE}
xaringanExtra::embed_xaringan(
  "https://matt-dray.github.io/targets-dsfest/",
  ratio = "4:3",
)
```

# {targets}

{targets} ‘remembers’ the relationships between objects in your workflow. When you update your analysis, {targets} makes sure that only the impacted objects are re-run. This means you don’t have to recreate everything from scratch each time.

# But...{drake}?

You may have noticed I cunningly plagiarised myself by re-using slides from [a presentation to Bioinformatics London](https://www.rostrum.blog/2020/01/31/reprobioinformatics/) in January 2020.

The difference is that that presentation was about {drake}, another workflow reproducibility package by Will Landau. So what's the difference between the two packages?