---
title: 'Blog for yourself'
author: 'Matt Dray'
date: '2020-02-21'
slug: get-blogging
categories:
  - blog-meta
tags: []
draft: yes
---

# tl;dr

Note to younger self: there are many reasons to start an R blog. Start by doing it for you.

# The big 5-0

I've stumbled into writing 50 posts on this blog. There was no plan. I have no strategy.

My only regret was not starting sooner. What would I advise my younger self?

1. It's your [reference library](#reference-library)
1. It only has to be [good enough](#good-enough)
1. There are others [like you](#like-you)

# 1. It's your reference library {#reference-library}

I forget everything. That's especially true for code.

Keeping a written record of what you've learnt is a good way of storing that information outside of your head.

Writing a narrative will help explain the code and make sure you understand it in your own words. That'll make it easier to pick up later.

It helps if what you write is available to you everywhere all the time as well. It needs to be open and on the internet. (Spoiler: that will make it easier for other people to find and use as well.)

For me, 'blog or it didn't happen' is probably a good mantra. If I don't write it down then I'll just forget what I did.

I've lost count of the number of times I've referred back to my own posts on [creating an R package](https://www.rostrum.blog/2019/11/01/usethis/), [web scraping](https://www.rostrum.blog/2019/03/04/polite-webscrape/) and [fixing leaky pipes](https://www.rostrum.blog/2019/04/07/fix-leaky-pipes/), for example. There are others out there, but I wrote these in my own words.

# 2. It only has to be good enough {#good-enough}

Perfectionism is cruel and the law of diminishing returns is strong. I sat on a thesis for months longer than I should have. Did it improve in that time? Marginally. Did it affect my grade? No.

One of the best pieces of advice I've ever been given is 'it only has to be good enough'. You have finite time and there's an infinite amount of stuff to do.

This is espeically true of writing blog posts for yourself. They only have to be good enough to remind you of what you did so you can redo it.

This also places emphasis emphasise keeping things simple and to the point so you can more easily refer back in future.

# 3. There are others like you {#like-you}

You don't owe anything to anyone. But there are other people like you.

You will get better by explaining things and sharing things.

I'm not a programmer. I'm not a software engineer. I wasn't trained in stats.

I took a required R class; I didn't get it. I slowly relearnt over four years of studies. I've been using it in a patchy way since I started my career five years ago.

There are other people in this position.

Lower the barrier to entry.

Inspiration from people like Sharla Gelfand and David Keyes, of R for the Rest of Us.

I've learnt by looking at other people's blogs.

RAP.

# Other



