---
title: Ninja scaffolding with {kunoichi}
author: Matt Dray
date: '2020-03-12'
slug: ninja-scaffold
categories:
  - code
  - tutorial
tags:
  - kunoichi
  - rmarkdown
  - xaringan
draft: yes
---


I've really taken to the [{xaringan}]() package by [Yihui Xie](), an implementaiton of [remark.js](), for creating reproducible slides with R.

Users have developed themes for {xaringan} and the CSS has been added to the package. Garrick Aden-Buie has made this process even easier with {xaringanthemer}, which lets you define themes using R code rather than getting mucky with the CSS.

Rather than theming, I've been interested recently in page layouts: how can I place items like plots and tables into defined 'segments' of a page? 

Sure, {xaringan} has things like `.pull-left[]` and `.pull-right[]` that can place content but this only goes so far for my particular need.

# Ninjutsu

[Emi Tanaka]()'s excellent [{kunoichi}]() package provides some excellent options for splitting slides into multiple sections.

Emi's `ninjutsu.css` file defines a number of page-split classes. For example, a `split-1-2-1` class that carves the page into three columns, where the middle one is twice the width (50% of the page) of the ones either side (25% each):

```{css, split121, eval=FALSE}
.split-1-2-1>.column:first-of-type {
  width: 25%; height: 100%; position: absolute; top: 0; left: 0; 
}
.split-1-2-1>.column:nth-of-type(2) {
  width: 50%; height: 100%; position: absolute; top: 0; left: 25%;
}
.split-1-2-1>.column:nth-of-type(3) {
  width: 25%; height: 100%; position: absolute; top: 0; right: 0;
}
```

To walk this through, each line defining the class has:

* the name of the class (`split-1-2-1`)
* the number of the column being defined within it (e.g. `.column:first-of-type` for the first one)
* the style definition for each column in the class (`width`, `height`, etc)

So the first column starts from the extreme left (`left: 0;`), the middle column starts where the first one ends (`left: 25%;`) and the third one starts from the extreme right (`right: 0;`).

# Hacking the hacker

Specifically, I wanted to define title, body and footer 'segments' for:

* a cover page
* a generic content page
* a content page that could show a table and plot next to each other, with a wider table underneath

This means I could colour them and fill them with content according to some additional CSS formatting.

To do this, I tweaked Emi's `split-1-2-1` class to create rows for each of the segments I wanted.

The title page has two rows, one is a large header area to hold a logo:

```{css, eval=FALSE}
.split-title>.row:first-of-type {
  height: 20%; width: 100%; position: absolute; top: 0; left: 0;
}
.split-title>.row:nth-of-type(2) {
  height: 80%; width: 100%; position: absolute; left: 0; top: 20%;
}
```

The main, generic slide, has a title and footer and a large blank area for content:

```{css, eval=FALSE}
.split-body1>.row:first-of-type {
  height: 8%; width: 100%; position: absolute; top: 0; left: 0;
}
.split-body1>.row:nth-of-type(2) {
  height: 87%; width: 100%; position: absolute; left: 0; bottom: 5%;
}
.split-body1>.row:nth-of-type(3) {
  height: 5%; width: 100%; position: absolute; bottom: 0; left: 0;
}
```

I've modified the main, generic slide so it's split once more:

```{css, eval=FALSE}
.split-body2>.row:first-of-type { 
  height: 8%; width: 100%; position: absolute; top: 0; left: 0;
  }
.split-body2>.row:nth-of-type(2) { 
  height: 43.5%; width: 100%; position: absolute; left: 0; top: 8%;
  }
.split-body2>.row:nth-of-type(3) { 
  height: 43.5%; width: 100%; position: absolute; left: 0; bottom: 5%;
  }
.split-body2>.row:nth-of-type(4) { 
  height: 5%; width: 100%; position: absolute; bottom: 0; left: 0;
  }
```