---
title: Rate my RStudio setup
author: Matt Dray
date: '2020-09-08'
slug: rstudio-settings
categories:
  - code
tags:
  - r
  - rstudio
  - rstudio-addins
draft: yes
---

# tl;dr

R has a big online community. RStudio is a popular GUI. Why is the intersection so sparse?

Here I expose my setup so you can criticise it. Or learn from it. Or both. Or neither.

# What we're working with

I spend most of my time in RStudio on a MacBook Air 13-inch (2017) running macOS Sierra with RStudio version 1.3.1073 and R version 3.6.1 (thanks to IT restrictions).

Click to jump to the section

* [theme](#theme)
* [font](#font)
* [layout](#layout)
* [RData](#rdata)
* [addins](#addins)
* [other GUI elements](#other-gui-elements)
* [keyboard shortcuts](#keyboard-shortcuts)


# Theme {#theme}

I'm using [the free viridis-theme](https://github.com/Z3tt/viridis-theme) by [Cédric Scherer](http://cedricscherer.netlify.app/). It's based on [the viridis colour palette](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) by [David Cooley](https://github.com/SymbolixAU/rstudiothemes/blob/master/viridis.tmTheme), which is designed for people with colour blindness.

I'm [red-green colourblind](https://en.wikipedia.org/wiki/Color_blindness) and the syntax highlighting of this theme lets me distinguish easily between the different code elements. It also helps that the colours are quite bright against a dark background. I want to be able to focus easily on the code itself, so I like that comments in this theme are italic and a closer colour to the background.

I also use syntax highlighting in the console. You can get this by checking the box at _Tools > Global Options > Code > Display > Show syntax highlighting in console input_.

Sometimes I switch to a light theme when writing text-rich blog posts. Syntax highlighting is less important in this instance and I find black-on-white text easier to read.

You can change to an inbuilt theme at _Tools > Global options > Appearance > Editor theme_. Click _Add..._ to provide a new theme from file.

# Font {#font}

I'm using FiraCode ([source](https://github.com/tonsky/FiraCode), [Google Fonts](https://fonts.google.com/specimen/Fira+Code)) a free font from Mozilla.

I find it easy to read both for coding and for writing prose.

It's main draw is its ligatures: it combines certain sets of adjacent characters so it looks like on character. For example, the assignment operator gets condensed from `<` and `-` to a single, unbroken arrow character.

# Layout {#layout}

I have the console pane on the right-hand side rather than the default of being on the left. I don't see a lot people doing this, but I tend to maximise the script and console panes side-by-side so I can focus purely on inputs and outputs.

You can change this setting by clicking the _Workspace Panes_ button (looks like a window) on the 'taskbar' at the top of the interface, to the left of the _Addins_ menu.

# RData {#rdata}

There are default settings that let RStudio open from where you left off, so that the contents of your environment are intact. [I don't like this](https://www.rostrum.blog/2020/04/17/r-self-shame/#env) and it's advised against in places like [the R for Data Science book](https://r4ds.had.co.nz/workflow-projects.html) by Wickham and Grolemund.

I tend to restart R every few minutes so that I'm working with a completely clean environment. This stops me from modifying objects and forgetting about it, which could result in erroneous output.

You can set this behaviour in _Tools > Global Options > General > Basic > Workspace_ by unchecking _Restore .Rdata on startup_ and setting _Save workspace to .RData on exit_ to _Never_.

# Addins {#addins}

RStudio has a system of 'addins' that act as extensions for RStudio. They let you execute shortcuts and other commands via a dropdown menu in the GUI or a keyboard shortcut. Often these are functions that relate to the GUI in some way, like modifying selected text.

I have a whole bunch of addins, but only use a few of them frequently enough to note here.

* {blogsnip} and {remedy}
* {datapasta}
* {blogdown}
* {annotater}
* {reprex}

There's no official catalogue for addins, but see a list in the readme for [{addinslist} by Dean Attali]. You can also install it as a kind of meta-addin and use it to browse for other addins.

# Other GUI elements {#other-gui-elements}

From the 'magic wand' menu:

* Reflow comment
* Insert roxygen skeleton
* Rename in scope

Other things:

* RStudio icon to navigate to the project or package home directory
* Show document outline

Some of these have keyboard shortcuts that I frequently forget.

# Keyboard shortcuts {#keyboard-shortcuts}

There's a number of default keyboard shortcuts that I use frequently:

* <kbd>Cmd</kbd> + <kbd>M</kbd> for a {magrittr} pipe, `%>%`
* <kbd>Cmd</kbd> + <kbd>-</kbd> for an assignment arrow, `<-`
* <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Fn</kbd> + <kbd>F10</kbd> `r emo::ji("octopus")` to restart RStudio
* <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> to comment out a selected block
* <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> to add a section label
* <kbd>Cmd</kbd> + <kbd>D</kbd> to document a package,  <kbd>Cmd</kbd> + <kbd>L</kbd> to load it

# For teaching

I revert a lot of these settings back to the defaults when teaching.

This makes things less confusing for learners and makes it easier to use shared language to describe stuff in the GUI.

# Next

I don't really make use of snippets and I haven't really mapped any new keyboard shortcuts. I want to look into Garrick Aden-Buie's {shrtcuts} package ([blog](https://www.garrickadenbuie.com/blog/shrtcts/), [package site](https://pkg.garrickadenbuie.com/shrtcts/)).

I tend to use the terminal window for everything Git based and I know very little of the Git GUI built into RStudio.