---
title: "Fun and learning. In a dungeon."
author: Matt Dray
date: '2023-03-15'
slug: in-a-dungeon
categories:
  - event
  - talk
tags:
  - r
  - r.oguelike
---

# tl;dr

Today I spoke at a public sector event for data scientists[^ds] in a UK Civil Service department.

The abstract:

> Ever done a technical training module and then immediately forgot what you learnt? Do you sometimes feel like you’re ticking boxes instead of actually developing your skills? Yeah, me too. Luckily, more active styles of learning are available. Maybe you can try working on a small, focused project where you can make mistakes and have fun. I’ve had success with this and, as a bonus, accidentally learnt more than I had planned to. I’ll give you an example of my experience and some ideas for how you might be able to do it yourself. The talk will involve a detour to an underground cave, but you won’t need any extra equipment.

# Slides

The slides are [available on the web](https://github.com/matt-dray/in-a-dungeon) (press 's' to open the speaker notes) and you can find [the source on GitHub](https://matt-dray.github.io/in-a-dungeon). 

Note that I was talking from personal experience rather than endorsing or commenting on any particular department's approaches.

<!--<iframe width="780" height="500" src="https://matt-dray.github.io/in-a-dungeon" title="Slides for 'Fun and learning. In a dungeon!'"></iframe>-->

I used [Revealjs via Quarto](https://quarto.org/docs/presentations/revealjs/) to make these.

# On my soapbox

Basically, I think 'module-based' learning—often passive video walkthroughs with comprehension exercises—are too generic and I usually struggle to remember anything from them.

I think 'project-based' learning is preferable. Think about what you actually want to learn and develop a small-scope, discrete project around it. Make the subject matter fun. Fail meaningfully by be being open, recording what you've found, and involving your community.

The contrived soundbite is that module-based is done _to_ you and project-based is done _by_ you.

Is this a new thought technology? No. Is it always true and applicable to everyone in every conceivable scenario and with every learning need? No. What's my expertise? None, really. I've just spent a long time in lots of different departments and I can tell you what has worked for me as someone who entered the public sector with little computing or coding ability.[^anecdote]

My example project was [{r.oguelike}](https://github.com/matt-dray/r.oguelike). This is an R package I wrote to achieve some learning goals and also to have some fun; it contains a novelty tile- and turn-based game that the player interacts with in the console. This also fit the themes of the conference—connectivity and patterns—because it contains [a procedural dungeon generator](https://www.rostrum.blog/2022/05/01/dungeon/) and [enemy pathfinding](https://www.rostrum.blog/2022/06/10/basic-search/).

---
<details><summary>Session info</summary>
```{r eval=TRUE, sessioninfo, echo=FALSE}
sessioninfo::session_info()
```
</details>

[^ds]: I'm becoming more convinced that I don't know what 'data scientist' means anymore. Old man yells at cloud (computing), etc.
[^anecdote]: Would've been smarter to bring, y'know, actual evidence to a data science conference, eh?